apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-deployment
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
        - name: app-api
          image: renancesu/prova-eliel:1
          ports:
            - containerPort: 3000
          env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: app-configmaps
                key: PORT
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: DATABASE_URL
          livenessProbe:
            httpGet:
              path: /pessoa
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 3
