services:
  postgres:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - my-bridge

  app1:
    build: .
    ports:
      - 3001:3000
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/my_db1
      PORT: 3001
    depends_on:
      - postgres
    networks:
      - my-bridge

  app2:
    build: .
    ports:
      - 3002:3000
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/my_db2
      PORT: 3002
    depends_on:
      - postgres
    networks:
      - my-bridge
  nginx:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
    networks:
      - my-bridge
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data: {}

networks:
  my-bridge:
    driver: bridge