apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      upstream app-service_upstream {
          server app-service:80;
      }

      server {
        listen 80;

        location / {
          proxy_pass http://app-service_upstream;
        }
      }
    }
