apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  selector:
    app: app2
  ports:
    - port: 3002
      targetPort: 3000

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: app1:latest
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres@postgres:5432/mydb"
            - name: PORT
              value: "3002"
          ports:
            - containerPort: 3000
