apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
      - configmaps
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: obodkiLYWbiKQUDQtEvUJK0x7FsdzvxyPtuBgI/1TMA=
      - identity: {}